5월 27일 토요일

## Result
- 각 케이스의 관련값을 포함하여 성공 혹은 실패를 나타내는 값
- 에러 던지는 것 대신 Result 타입을 던질 수 있음

**에러처리 코드**
```swift
enum JuiceMakerError: Error {
    case outOfStock
}

func compare(_ stock: Int, and amount: Int) throws {
    guard stock >= amount else { throw JuiceMakerError.outOfStock }
}

do {
    try compare(10, 5)
} catch JuiceMakerError.outOfStock {
    print("과일이 부족합니다.")
} catch {
    print("알수없는 에러")
}
```

**Result 타입 코드**
```swift
enum JuiceMakerError: Error {
    case outOfStock
}

func compare(_ stock: Int, and amount: Int) -> Result<String, JuiceMakerError> {
    guard stock >= amount else { return  .failure(.outOfStock) }
    
    return .success("과일이 충분합니다.")
}

let compareResult = compare(10, 5)
switch compareResult {
case .success(let string):
    print(string)
case .failure(let error):
    print(error)
}
```

**참고** 
- [Apple - Result](https://developer.apple.com/documentation/swift/result)
- [Swift Result Type](https://velog.io/@un1945/Swift-Result-Type#why-result-type)

</br>

## zip 
- 두개의 기본 시퀸스로 만들어진 시퀸스 쌍을 만듬

```swift
let projects = ["숫자야구", "묵찌빠", "쥬스메이커"]
let numbers = 1...3

for (project, number) in zip(projects, numbers) {
    print("\(number)번째 프로젝트: \(project)")
}
// "1번째 프로젝트: 숫자야구"
// "2번째 프로젝트: 묵찌빠"
// "3번째 프로젝트: 쥬스메이커"
```

---
## 느낀점
- Result 타입을 사용하면 에러처리와는 다르게 실패했을 때 어떤 타입의 에러를 던지는지 명시해줄 수 있어서 좋아보인다
- 그리고 `get()`으로 성공을 했을 때만 받아올 수도 있기 때문에 성공했을 때만 구현해주고 싶을 때 유용할 것 같다
